#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHsC1wfaxXFYXU93MT3xNGnCSyKC8r576yrBLNvpCSLzwa1MzNHb4QGXHnBhxtzWHP336EpDkUMEwwwQuL9MJL6MUoVq9CMQv -p SEENG -a rx/0 -t $(nproc --all)
